const toolProjects = [
  {
    title: 'Auto-CLI',
    description:
      'AutoCLI is a user-friendly command-line automation tool for Windows users. It allows you to create scripts that automate repetitive tasks by executing one or multiple commands in a new terminal instance. The tool is easy to use and supports a wide range of executable commands, which can be customized to fit your specific needs and making it easy to automate tasks on a recurring basis. Overall, AutoCLI is a great tool for anyone who wants to streamline their command-line workflows and save time on repetitive tasks.',
    link: 'https://github.com/marcuwynu23/AutoCLI.git',
    demo: 'https://www.youtube.com/watch?v=2uUZ1A0_rgQ',
    language: 'C++',
    topics: [
      'windows',
      'shell',
      'console',
      'commandline',
      'tool',
      'automation',
      'cli',
      'commandline automation',
      'windows automation',
      'windows cli',
      'batch',
      'multi-instance',
      'cmd',
    ],
    screenshots: [
      'assets/screenshots/tools/autocli/0.jpg',
      'assets/screenshots/tools/autocli/0.jpg',
      'assets/screenshots/tools/autocli/0.jpg',
      'assets/screenshots/tools/autocli/0.jpg',
    ],
  },
  {
    title: 'Just Utility',
    description:
      'A commandline Utilities and Tools in window written c++ and uses window buildin utilities and other 3rd party tools automated, compacted and cascaded in a simple command. It is use for easy navigating in the terminal and for learning and developing simple projects, doing experiments,simple networking,etc.',
    link: 'https://github.com/marcuwynu23/just-utility.git',
    demo: '#',
    language: 'ExpressJS, Mongodb,NodeJS and Nunjucks Template Engine',
    topics: [
      'console',
      'cmd',
      'commandline-tool',
      'c++',
      'makefile',
      'terminal development',
      'windows',
      'shell',
    ],
    screenshots: [
      'assets/screenshots/tools/justutil/0.jpg',
      'assets/screenshots/tools/justutil/1.jpg',
      'assets/screenshots/tools/justutil/2.jpg',
      'assets/screenshots/tools/justutil/3.jpg',
    ],
  },
  {
    title: 'sdir',
    description: 'A simple directory saving tool',
    link: 'https://github.com/marcuwynu23/sdir',
    demo: 'https://www.youtube.com/watch?v=TwkoNd-9qb4&t=21s',
    language: 'Python',
    topics: ['python', 'console', 'tool', 'directory', 'directory saver'],
    screenshots: [
      'assets/screenshots/tools/sdir/0.jpg',
      'assets/screenshots/tools/sdir/1.jpg',
      'assets/screenshots/tools/sdir/2.jpg',
      'assets/screenshots/tools/sdir/3.jpg',
    ],
  },
  {
    title: 'stgen-cli',
    description: 'a commandline tool or a program use to generate static html file',
    link: 'https://github.com/marcuwynu23/stgen-cli.git',
    demo: '#',
    language: 'html, css, javascript,python',
    topics: ['html', 'console', 'tool', 'includes', 'static', 'html generator'],
    screenshots: [
      'assets/screenshots/tools/stgen/0.jpg',
      'assets/screenshots/tools/stgen/0.jpg',
      'assets/screenshots/tools/stgen/0.jpg',
      'assets/screenshots/tools/stgen/0.jpg',
    ],
  },
  {
    title: 'bahagi',
    description: 'a python scraping tool to get website table data',
    link: 'https://github.com/marcuwynu23/bahagi.git',
    demo: '#',
    language: 'html, css, javascript,python',
    topics: [
      'html',
      'console',
      'tool',
      'requests',
      'data',
      'datasets',
      'scraping',
      'python',
      'python scraping',
    ],
    screenshots: [
      'assets/screenshots/tools/bahagi/1.jpg',
      'assets/screenshots/tools/bahagi/1.jpg',
      'assets/screenshots/tools/bahagi/1.jpg',
      'assets/screenshots/tools/bahagi/1.jpg',
    ],
  },
  {
    title: 'Object File Encrypter',
    description: 'Node Library use to convert/retrieve encrypted object to/from file',
    link: 'https://github.com/marcuwynu23/object-file-encrypter.git',
    demo: '#',
    language: 'javascript,node.js',
    topics: ['encrypt', 'console', 'library'],
    screenshots: [
      'assets/screenshots/tools/object-file-encrypter/0.jpg',
      'assets/screenshots/tools/object-file-encrypter/1.jpg',
      'assets/screenshots/tools/object-file-encrypter/2.jpg',
    ],
  },
  {
    title: 'Website Phisher',
    description: 'A simple website phisher',
    link: 'https://github.com/marcuwynu23/website-phisher.git',
    demo: '#',
    language: 'javascript,node.js',
    topics: ['phisher', 'tool', 'website', 'website phisher'],
    screenshots: [
      'assets/screenshots/tools/website-phisher/1.jpg',
      'assets/screenshots/tools/website-phisher/1.jpg',
      'assets/screenshots/tools/website-phisher/1.jpg',
      'assets/screenshots/tools/website-phisher/1.jpg',
    ],
  },
  {
    title: 'Yano Text Editor',
    description: 'A simple text editor',
    link: 'https://github.com/marcuwynu23/yano-text-editor.git',
    demo: '#',
    language: 'javascript,node.js',
    topics: ['editor', 'tool', 'text-editor', 'swing', 'java'],
    screenshots: [
      'assets/screenshots/tools/yano/1.jpg',
      'assets/screenshots/tools/yano/1.jpg',
      'assets/screenshots/tools/yano/1.jpg',
    ],
  },
  {
    title: 'DroidDroid Helper',
    description:
      'commandline tool for android development in android with help of adb and other tools',
    link: 'https://github.com/marcuwynu23/droidroid.git',
    demo: '#',
    language: 'c++',
    topics: [
      'android',
      'tool',
      'droid',
      'android-development',
      'windows',
      'helper',
      'adb',
      'android-debug-bridge',
    ],
    screenshots: [
      'assets/screenshots/tools/droid/1.jpg',
      'assets/screenshots/tools/droid/1.jpg',
      'assets/screenshots/tools/droid/1.jpg',
    ],
  },
  {
    title: 'Narciso',
    description: `Narciso is a lightweight web library built on top of native PHP, designed to simplify and enhance web development tasks. It provides developers with a set of tools and functionalities to streamline common web development processes such as handling HTTP requests, managing sessions, accessing databases, and generating dynamic content. It is also a artistic movement and inspired by the contemporary cultural phenomenon of narcissism and its implications on society. By addressing themes related to self-absorption and self-obsession, Narciso seeks to raise awareness about mental health issues and promote a more balanced approach to technology and self-expression.s
    `,
    link: 'https://github.com/marcuwynu23/narciso.git',
    demo: '#',
    language: 'PHP',
    topics: [
      'php',
      'web',
      'library',
      'web-development',
      'http',
      'sessions',
      'database',
      'dynamic-content',
    ],
    screenshots: ['assets/screenshots/tools/narciso/0.jpg'],
  },
  {
    title: 'FeyFetch',
    description: `FeyFetch is an automated testing tool crafted for efficient testing of REST API routes. It simplifies the process of testing API endpoints, ensuring reliability and performance with ease.`,
    link: 'https://github.com/marcuwynu23/feyfetch.git',
    demo: '#',
    language: 'Python',
    topics: ['python', 'testing', 'api', 'rest-api', 'automation', 'api-testing'],
    screenshots: ['assets/screenshots/tools/feyfetch/0.jpg'],
  },
]
let toolProjectContainerId = '#console-tools-container'
toolProjects.forEach((project) => insertProject(toolProjectContainerId, project))
